### ISSUE TITLE
The validity VS. max-allowed-end parameter in generic-schedule-params grouping

### ISSUE THREAD

**Issue by QiufangMa** [netmod-wg/schedule-yang#11]
How to understand the difference between the validity and max-allowed-end? Both seem refer to a maximum time upper limit.
https://github.com/netmod-wg/schedule-yang/blob/main/yang/ietf-schedule.yang#L240
https://github.com/netmod-wg/schedule-yang/blob/main/yang/ietf-schedule.yang#L268

**Comment by boucadair** [comment]
As indicated in the text, what takes precedence is the validity. 

Validity controls when a schedule can be executed independent of when that a schedule ends. The other one is more specific as it reasons about  when a scheduled event will ends. Having both is still OK as soon as we are clear about the one that takes precedence (which we do). This provides more flexibility to the "consumers" of the common model. 

Thanks
