### ISSUE TITLE
Add an RFC8413-like example

### ISSUE THREAD

**Issue by boucadair** [netmod-wg/schedule-yang#19]
https://datatracker.ietf.org/doc/html/rfc8413

**Comment by QiufangMa** [comment]
Can you give me the section number in 8413 where the examples we can imitate?

**Comment by boucadair** [comment]
The example can be drawn with a ref to this part: this is a simple start/end time schedule.

[4.1](https://datatracker.ietf.org/doc/html/rfc8413#section-4.1).  Service Request

   As shown in Figure 2, some component in the network requests a
   service.  This may be an application, an NMS, an LSR, or any
   component that qualifies as a Path Computation Client (PCC).  We show
   this on the figure as the "Service Requester", and it sends a request
   to the PCE for an LSP to be set up at some time (either now or in the
   future).  The request, indicated on Figure 2 by the arrow (a),
   includes all of the parameters of the LSP that the requester wishes
   to supply, such as priority, bandwidth, start time, and end time.
   Note that the requester in this case may be the LSR shown in the
   figure or may be a distinct system.

**Comment by QiufangMa** [comment]
This seems about how the scheduling could be managed/implemented, but I am not sure if this falls within our scope.

**Comment by boucadair** [comment]
What we need to show is that how the simple period structure is sufficient for this case.

**Comment by boucadair** [comment]
fixed in #35
